### PR TITLE
Update to CentOS Stream9

### PR DESCRIPTION
**Pull request by slintes**
#### Why we need this PR
Container build fails because of invalid yum repo config.

#### Changes made
Update to CentOS Stream9, Stream8 is EOL

### CODE REVIEW

**Comment by slintes** [comment]
needs https://github.com/openshift/release/pull/53876

**Review by clobrano — APPROVED** [review]

**Comment by slintes** [comment]
4.16 succeeded on #151 🤔 

/test 4.15-openshift-e2e
/test 4.16-openshift-e2e

**Comment by slintes** [comment]
network issue?

/retest

**Pull request merged**
