### PR TITLE
GitHub CI Tests

### PR DESCRIPTION
**Pull request by razo7**
- Add pre-submit, and post-submit jobs.
- Add `test-no-verify` target.

### CODE REVIEW

**Comment by razo7** [comment]
Merge #11 first in order to test the pre-submit job

**Comment by slintes** [comment]
> Merge #11 first in order to test the pre-submit job

I think it makes more sense to merge this one first, so the new unit test is actually executed on its PR?

/lgtm
/hold

**Comment by razo7** [comment]
> > Merge #11 first in order to test the pre-submit job
> 
> I think it makes more sense to merge this one first, so the new unit test is actually executed on its PR?
> 
> /lgtm /hold

It does make sense. 
/unhold

**Pull request merged**
