### PR TITLE
Minimize Reboot Test Pod Warnings of PSA

### PR DESCRIPTION
**Pull request by razo7**
The reboot test pod needs privilage permissions for fetching the node's boot time, and these permissions can be minimized.

### CODE REVIEW

**Comment by mshitrit** [comment]
/lgtm
/hold
giving others chance to review

**Comment by clobrano** [comment]
/lgtm

Giving a chance to get more feedbacks, feel free to unhold
/hold

**Comment by razo7** [comment]
#68 is going to use the test pod and for stooping Kubelet `HostPID:     true` should be defined in the spec of the testing pod. Thus I am revering this change.

**Comment by razo7** [comment]
\unhold

**Pull request merged**
