### PR TITLE
Remove redundant VoulmeAttachment from testing

### PR DESCRIPTION
**Pull request by razo7**
#### Why we need this PR

VoulmeAttachment is no longer removed from the resource deletion strategy, thus it is no longer needed for testing. Follow up to #102 .

#### Changes made

Remove VoulmeAttachment creation and deletion in unit-test.

### CODE REVIEW

**Review by clobrano — APPROVED** [review]

**Comment by razo7** [comment]
**_tide_** job is not responding, so I am pushing old commit as a new one to retrigger tide (with the many other tests)...

**Comment by slintes** [comment]
/hold

need to fix CI config for having e2e tests required

**Pull request merged**
