### PR TITLE
Publish FAR to Stable Channel

### PR DESCRIPTION
**Pull request by razo7**
Getting ready to new release and with the workload deletion logic FAR can be ~~subscribed~~ published to the `stable`  channel.

### CODE REVIEW

**Comment by razo7** [comment]
I think the channel in CI should be updated as well ([`OO_CHANNEL: candidate`](https://github.com/openshift/release/blob/master/ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main__4.14.yaml#L36)).

**Review by slintes — APPROVED** [review]

**Comment by razo7** [comment]
I am unsure why VA was not been deleted on the first e2e test on OCP 4.12. I am pretty confident that it is unrelated to the PR change.
/retest

**Pull request merged**
