### PR TITLE
Add fence_gce Agent for GCP

### PR DESCRIPTION
**Pull request by razo7**
Adding a fence agent for Google Cloud Platform (GCP) platform - [fence_gce](https://www.mankier.com/8/fence_gce)

### CODE REVIEW

**Comment by clobrano** [comment]
/lgtm
out of curiosity, how big the image would result after this addition?
/hold
feel free to unhold

**Comment by razo7** [comment]
>out of curiosity, how big the image would result after this addition?

Before it was 159.7 MiB, and with the new agent it is 160.9 MiB, so the new image is only adding 1.2 MiB.

/unhold

**Pull request merged**
