### PR TITLE
Channel and Image Update

### PR DESCRIPTION
**Pull request by razo7**
Apply #1 changes by running `make bundle` :

- Set image to Medik8s quay repository.
- Set the bundle's channel and default channel to be `candidate`.

### CODE REVIEW

**Review by clobrano — COMMENTED** [review]
/lgtm

Giving others a chance to review as well, feel free to unhold

/hold

**Comment by razo7** [comment]
Even though this is the first release of FAR we set the [bundle's channel and default channel](https://olm.operatorframework.io/docs/best-practices/channel-naming/#recommended-channel-naming) to be 'stable`.

**Pull request merged**
